import type { Project } from '../model/types'

export const PROJECTS: Project[] = [
  {
    id: 'white-peak-house',
    number: '01',
    title: '白岳の家',
    titleEn: 'White Peak House',
    category: '住宅',
    location: '滋賀県',
    year: 2023,
    area: 187,
    description: '山の稜線を映した切妻屋根と大開口。光と影が季節とともに移ろう、静謐な住まい。',
  },
  {
    id: 'axis-tower',
    number: '02',
    title: 'AXIS TOWER',
    titleEn: 'Axis Tower',
    category: 'オフィス',
    location: '東京都',
    year: 2022,
    area: 3200,
    description: '軸線と透明性を設計言語とした高層オフィス。構造体そのものが立面のグラフィックとなる。',
  },
  {
    id: 'aoyama-residence',
    number: '03',
    title: '青山レジデンス',
    titleEn: 'Aoyama Residence',
    category: '集合住宅',
    location: '東京都',
    year: 2023,
    area: 1850,
    description: '都市の密度の中に微気候をつくる集合住宅。外部テラスと共用庭が住民の交差点となる。',
  },
  {
    id: 'hiro-pavilion',
    number: '04',
    title: 'HIRO PAVILION',
    titleEn: 'Hiro Pavilion',
    category: '商業施設',
    location: '大阪府',
    year: 2022,
    area: 420,
    description: '街路に開いたパビリオン型商業施設。折板屋根が内外の境界を曖昧にする。',
  },
  {
    id: 'museum-of-light',
    number: '05',
    title: '光の美術館',
    titleEn: 'Museum of Light',
    category: '文化施設',
    location: '神奈川県',
    year: 2021,
    area: 2100,
    description: 'トップライトと傾斜壁が生む光の劇場。作品と空間が同等の存在感を持つ美術館。',
  },
  {
    id: 'lakeside-retreat',
    number: '06',
    title: '湖畔の山荘',
    titleEn: 'Lakeside Retreat',
    category: 'ヴィラ',
    location: '長野県',
    year: 2023,
    area: 145,
    description: '湖面を切り取るピクチャーウィンドウと水平に伸びる大庇。四季を額装する山の別荘。',
  },
]
